/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import java.awt.Dimension;
import Clases.WebServiceClient;

/**
 *
 * @author Anderson
 */
public class Administrador_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Estudiante
     */
    public Administrador_Menu() {
        initComponents();
        this.setLocationRelativeTo(null);//Para centrar el form
    }

    WebServiceClient obj1 = new WebServiceClient();

    //Encargado_Canchas Cancha = new Encargado_Canchas();
    Administrador_Usuarios AgregarAlumnos = new Administrador_Usuarios();
    Administrador_Canchas ACanchas = new Administrador_Canchas();
    Alumno_Solicitudes ASolicitud = new Alumno_Solicitudes();
    Canchas Canchas = new Canchas();
    Reservaciones Reservacion = new Reservaciones();
    Alumnos_Horarios AHora = new Alumnos_Horarios();
    Encargado_Solicitudes ESolicitud = new Encargado_Solicitudes();
    Encargado_Horarios EHora = new Encargado_Horarios();
    Encargado_Historial Registro = new Encargado_Historial();

    public void Cerrar() {
        ASolicitud.setVisible(false);
        ESolicitud.setVisible(false);
        EHora.setVisible(false);
        Canchas.setVisible(false);
        Reservacion.setVisible(false);
        AHora.setVisible(false);
        EHora.setVisible(false);
        Registro.setVisible(false);
        ACanchas.setVisible(false);
        AgregarAlumnos.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cboPanel1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        cboPanel2 = new javax.swing.JComboBox<>();
        cboPanel3 = new javax.swing.JComboBox<>();
        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblInicios = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblInicio = new javax.swing.JLabel();
        btnUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cboPanel1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Registros--", "Alumnos", "Canchas", "Horarios", "Solicitudes" }));
        cboPanel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPanel1ActionPerformed(evt);
            }
        });
        jPanel1.add(cboPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 130, -1));

        jButton1.setText("Cerrar Sesión");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 130, -1));

        cboPanel2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Consultas--", "Canchas", "Horarios", "Reservaciones", "Registros" }));
        cboPanel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPanel2ActionPerformed(evt);
            }
        });
        jPanel1.add(cboPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 130, -1));

        cboPanel3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Solicitar--", "Canchas" }));
        cboPanel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPanel3ActionPerformed(evt);
            }
        });
        jPanel1.add(cboPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 130, 550));

        panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo (1).jpg"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo (2).jpg"))); // NOI18N

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(41, 41, 41))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(226, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(45, 45, 45))
        );

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 760, 550));

        lblInicios.setFont(new java.awt.Font("Arial Black", 3, 15)); // NOI18N
        lblInicios.setText("Administrador");
        getContentPane().add(lblInicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 40));

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInicio.setFont(new java.awt.Font("Cascadia Mono", 2, 24)); // NOI18N
        lblInicio.setForeground(new java.awt.Color(255, 255, 255));
        lblInicio.setText("Inicio");
        jPanel2.add(lblInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 360, 50));

        btnUsuario.setText("Usuario");
        jPanel2.add(btnUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 760, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboPanel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPanel1ActionPerformed
        // TODO add your handling code here:
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        if (cboPanel1.getSelectedItem().toString().equals("Alumnos")) {

            AgregarAlumnos.setPreferredSize(new Dimension(730, 460));  // Tamaño preferido
            panel.add(AgregarAlumnos);
            Cerrar();
            // Forzar el tamaño del componente
            AgregarAlumnos.setSize(760, 550); // Establecer el tamaño físico real
            Dimension tCont = panel.getSize();
            // Calcular la posición para centrar el componente
            int x = (tCont.width - AgregarAlumnos.getWidth()) / 2;
            int y = (tCont.height - AgregarAlumnos.getHeight()) / 2;
            // Establecer la ubicación del componente
            AgregarAlumnos.setLocation(x, y);
            // Actualizar la visualización y repintar
            panel.revalidate();  // Asegura que el panel se actualice
            panel.repaint();     // Vuelve a dibujar el panel
            AgregarAlumnos.setVisible(true);
            lblInicio.setText("Gestion de usuarios");
        } else if (cboPanel1.getSelectedItem().equals("Canchas")) {
            Cerrar();
            ACanchas.setPreferredSize(new Dimension(760, 550));
            panel.add(ACanchas);
            ACanchas.setSize(730, 460);
            Dimension tCont = panel.getSize();
            int x = (tCont.width - ACanchas.getWidth()) / 2;
            int y = (tCont.height - ACanchas.getHeight()) / 2;
            ACanchas.setLocation(x, y);
            panel.revalidate();  // Asegura que el panel se actualice
            panel.repaint();     // Vuelve a dibujar el panel
            ACanchas.setVisible(true);
            lblInicio.setText("Registro de canchas");
        } else if (cboPanel1.getSelectedItem().equals("Horarios")) {
            Cerrar();
            EHora.setPreferredSize(new Dimension(760, 550));
            panel.add(EHora);
            EHora.setSize(730, 460);
            Dimension tCont = panel.getSize();
            int x = (tCont.width - EHora.getWidth()) / 2;
            int y = (tCont.height - EHora.getHeight()) / 2;
            EHora.setLocation(x, y);
            panel.revalidate();  // Asegura que el panel se actualice
            panel.repaint();     // Vuelve a dibujar el panel
            EHora.setVisible(true);
            lblInicio.setText("Administracion de Horarios");
        } else if (cboPanel1.getSelectedItem().equals("Solicitudes")) {
            Cerrar();
            ESolicitud.setPreferredSize(new Dimension(760, 550));
            panel.add(ESolicitud);
            ESolicitud.setSize(730, 460);
            Dimension tCont = panel.getSize();
            int x = (tCont.width - ESolicitud.getWidth()) / 2;
            int y = (tCont.height - ESolicitud.getHeight()) / 2;
            ESolicitud.setLocation(x, y);
            panel.revalidate();  // Asegura que el panel se actualice
            panel.repaint();     // Vuelve a dibujar el panel
            ESolicitud.setVisible(true);
            lblInicio.setText("Solicitudes enviadas");
        }
    }//GEN-LAST:event_cboPanel1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        obj1.Privilegio = 0;
        obj1.Privilegio = 0;
        obj1.nombre = "";
        obj1.apellido = "";
        obj1.Correo = "";
        Login log = new Login();
        this.hide();
        this.dispose();
        //System.exit(0);
        log.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void cboPanel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPanel2ActionPerformed
        // TODO add your handling code here:
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        if (cboPanel2.getSelectedItem().toString().equals("Horarios")) {

            AHora.setPreferredSize(new Dimension(730, 460));  // Tamaño preferido
            panel.add(AHora);
            Cerrar();
            // Forzar el tamaño del componente
            AHora.setSize(760, 550); // Establecer el tamaño físico real
            Dimension tCont = panel.getSize();
            // Calcular la posición para centrar el componente
            int x = (tCont.width - AHora.getWidth()) / 2;
            int y = (tCont.height - AHora.getHeight()) / 2;
            // Establecer la ubicación del componente
            AHora.setLocation(x, y);
            // Actualizar la visualización y repintar
            panel.revalidate();  // Asegura que el panel se actualice
            panel.repaint();     // Vuelve a dibujar el panel
            AHora.setVisible(true);
            lblInicio.setText("Horarios disponibles");
        } else if (cboPanel2.getSelectedItem().equals("Canchas")) {
            Cerrar();
            Canchas.setPreferredSize(new Dimension(760, 550));
            panel.add(Canchas);
            Canchas.setSize(730, 460);
            Dimension tCont = panel.getSize();
            int x = (tCont.width - Canchas.getWidth()) / 2;
            int y = (tCont.height - Canchas.getHeight()) / 2;
            Canchas.setLocation(x, y);
            panel.revalidate();  // Asegura que el panel se actualice
            panel.repaint();     // Vuelve a dibujar el panel
            Canchas.setVisible(true);
            lblInicio.setText("Canchas disponibles");

        } else if (cboPanel2.getSelectedItem().equals("Reservaciones")) {
            Cerrar();
            Reservacion.setPreferredSize(new Dimension(760, 550));
            panel.add(Reservacion);
            Reservacion.setSize(730, 460);
            Dimension tCont = panel.getSize();
            int x = (tCont.width - Reservacion.getWidth()) / 2;
            int y = (tCont.height - Reservacion.getHeight()) / 2;
            Reservacion.setLocation(x, y);
            panel.revalidate();  // Asegura que el panel se actualice
            panel.repaint();     // Vuelve a dibujar el panel
            Reservacion.setVisible(true);
            lblInicio.setText("Reservaciones disponibles");

        } else if (cboPanel2.getSelectedItem().equals("Registros")) {
            Cerrar();
            Registro.setPreferredSize(new Dimension(760, 550));
            panel.add(Registro);
            Registro.setSize(730, 460);
            Dimension tCont = panel.getSize();
            int x = (tCont.width - Registro.getWidth()) / 2;
            int y = (tCont.height - Registro.getHeight()) / 2;
            Registro.setLocation(x, y);
            panel.revalidate();  // Asegura que el panel se actualice
            panel.repaint();     // Vuelve a dibujar el panel
            Registro.setVisible(true);
            lblInicio.setText("Registros");
        }
    }//GEN-LAST:event_cboPanel2ActionPerformed

    private void cboPanel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPanel3ActionPerformed
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        if (cboPanel3.getSelectedItem().toString().equals("Canchas")) {
            Cerrar();
            ASolicitud.setPreferredSize(new Dimension(730, 460));
            panel.add(ASolicitud);
            ASolicitud.setSize(730, 460);
            Dimension tCont = panel.getSize();
            int x = (tCont.width - ASolicitud.getWidth()) / 2;
            int y = (tCont.height - ASolicitud.getHeight()) / 2;
            ASolicitud.setLocation(x, y);
            panel.revalidate();  // Asegura que el panel se actualice
            panel.repaint();     // Vuelve a dibujar el panel
            ASolicitud.setVisible(true);
            lblInicio.setText("Solicitar cancha");
        }
    }//GEN-LAST:event_cboPanel3ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUsuario;
    private javax.swing.JComboBox<String> cboPanel1;
    private javax.swing.JComboBox<String> cboPanel2;
    private javax.swing.JComboBox<String> cboPanel3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblInicios;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
