/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Formularios;

import Clases.WebServiceClient;
import com.mycompany.soapclient.Cancha;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anderson
 */
public class Canchas extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    WebServiceClient obj1 = new WebServiceClient();

    public Canchas() {
        initComponents();
        cargarTablaCanchas();
    }

    private void cargarTablaCanchas() {
        jTable2.setDefaultEditor(Object.class, null);
        List<Cancha> canchas;
        if (cboCancha.getSelectedItem().toString().equals("Tipo")) {
            canchas = obj1.obtenerCanchas(txtBuscar.getText(), null, null, null);  // Método que obtiene la lista de canchas desde el servicio (puedes pasar los parámetros adecuados)
        } else if (cboCancha.getSelectedItem().toString().equals("Nombre")) {
            canchas = obj1.obtenerCanchas(null, txtBuscar.getText(), null, null);
        } else if (cboCancha.getSelectedItem().toString().equals("Numero de cancha")) {
            canchas = obj1.obtenerCanchas(null, null, txtBuscar.getText(), null);
        } else if (cboCancha.getSelectedItem().toString().equals("Estado")) {
            if (txtBuscar.getText().equals ("Activo")) {
                canchas = obj1.obtenerCanchas(null, null, null, "1");
            } else if (txtBuscar.getText().equals("Inactivo")) {
                canchas = obj1.obtenerCanchas(null, null, null, "0");
            } else {
                
                canchas = obj1.obtenerCanchas(null, null, null, null);
            }
        } else {

            canchas = obj1.obtenerCanchas(null, null, null, null);
        }

        // Definir las columnas de la tabla
        String[] columnas = {"Tipo", "Nombre","Ubicacion", "Número de Cancha", "Estado"};

        // Crear el modelo de la tabla con las columnas
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0);

        // Verificar si la lista de canchas no está vacía
        if (canchas != null && !canchas.isEmpty()) {
            // Llenar el modelo con las canchas
            for (Cancha cancha : canchas) {
                // Obtener los valores de cada cancha
                Object[] fila = {
                    cancha.getTipo() != null ? cancha.getTipo().getValue() : "No disponible", // Verifica que 'tipo' no sea nulo
                    cancha.getNombre() != null ? cancha.getNombre().getValue() : "No disponible", // Verifica que 'nombre' no sea nulo
                    cancha.getDireccion() != null ? cancha.getDireccion().getValue() : "No disponible",
                    cancha.getNumeroCancha() > 0 ? cancha.getNumeroCancha().byteValue() : "No disponible", // Verifica que el 'numeroCancha' sea válido
                    cancha.getEstado() == 1 ? "Activo" : "Inactivo"// Convierte el estado booleano a texto
                };
                modelo.addRow(fila);  // Añadir la fila al modelo
            }
        } else {
            // Si no se encontraron canchas, mostrar un mensaje de advertencia en la tabla
            Object[] fila = {"No hay canchas disponibles", "", "", ""};
            modelo.addRow(fila);  // Añadir una fila vacía para mostrar el mensaje
        }

        // Asignar el modelo de datos a la tabla
        jTable2.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        cboCancha = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(720, 460));
        jPanel3.setPreferredSize(new java.awt.Dimension(730, 460));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 710, 350));

        jLabel1.setText("Buscar");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        jPanel3.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 410, -1));

        cboCancha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione--", "Tipo", "Nombre", "Numero de cancha", "Estado" }));
        cboCancha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCanchaActionPerformed(evt);
            }
        });
        jPanel3.add(cboCancha, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, -1));

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
        cargarTablaCanchas();
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void cboCanchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCanchaActionPerformed
        // TODO add your handling code here:
        try{
        cargarTablaCanchas();
        txtBuscar.setText("");
        }catch(Exception x)
        {
            
        }
    }//GEN-LAST:event_cboCanchaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
        cargarTablaCanchas();
        txtBuscar.setText("");
        }catch(Exception x)
        {
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboCancha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
