/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import java.awt.Dimension;
import Clases.WebServiceClient;

/**
 *
 * @author Anderson
 */
public class Encargado_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Estudiante
     */
    public Encargado_Menu() {
        initComponents();
        this.setLocationRelativeTo(null);//Para centrar el form
    }

    WebServiceClient obj1 = new WebServiceClient();

    Encargado_Solicitudes Solicitud = new Encargado_Solicitudes();
    Canchas Cancha = new Canchas();
    Reservaciones Reservacion = new Reservaciones();
    Encargado_Horarios Hora = new Encargado_Horarios();
    Encargado_Historial Registro = new Encargado_Historial();

    public void Cerrar() {
        Solicitud.setVisible(false);
        Cancha.setVisible(false);
        Reservacion.setVisible(false);
        Hora.setVisible(false);
        Registro.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cboPanel2 = new javax.swing.JComboBox<>();
        cboPanel1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblInicios = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblInicio = new javax.swing.JLabel();
        btnUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cboPanel2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Reportes--", "Reporte de reservas" }));
        cboPanel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPanel2ActionPerformed(evt);
            }
        });
        jPanel1.add(cboPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 130, -1));

        cboPanel1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Registros--", "Canchas", "Solicitudes", "Reservaciones", "Horarios" }));
        cboPanel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPanel1ActionPerformed(evt);
            }
        });
        jPanel1.add(cboPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 83, 130, -1));

        jButton1.setText("Cerrar Sesión");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 130, 460));

        panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo (1).jpg"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo (2).jpg"))); // NOI18N

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(19, 19, 19))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(25, 25, 25))
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 730, 460));

        lblInicios.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        lblInicios.setText("Encargado");
        getContentPane().add(lblInicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 40));

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInicio.setFont(new java.awt.Font("Cascadia Mono", 2, 24)); // NOI18N
        lblInicio.setForeground(new java.awt.Color(255, 255, 255));
        lblInicio.setText("Inicio");
        jPanel2.add(lblInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 360, 50));

        btnUsuario.setText("Usuario");
        jPanel2.add(btnUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 730, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboPanel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPanel1ActionPerformed
        // TODO add your handling code here:
        
        
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        if (cboPanel1.getSelectedItem().toString().equals("Canchas")) {

            Cancha.setPreferredSize(new Dimension(730, 460));  // Tamaño preferido
            panel.add(Cancha);
            Cerrar();
            // Forzar el tamaño del componente
            Cancha.setSize(730, 460); // Establecer el tamaño físico real
            Dimension tCont = panel.getSize();
            // Calcular la posición para centrar el componente
            int x = (tCont.width - Cancha.getWidth()) / 2;
            int y = (tCont.height - Cancha.getHeight()) / 2;
            // Establecer la ubicación del componente
            Cancha.setLocation(x, y);
            // Actualizar la visualización y repintar
            panel.revalidate();  // Asegura que el panel se actualice
            panel.repaint();     // Vuelve a dibujar el panel
            Cancha.setVisible(true);
            lblInicio.setText("Canchas");
        } else if (cboPanel1.getSelectedItem().equals("Reservaciones")) {
            Cerrar();
            Reservacion.setPreferredSize(new Dimension(730, 460));
            panel.add(Reservacion);
            Reservacion.setSize(730, 460);
            Dimension tCont = panel.getSize();
            int x = (tCont.width - Reservacion.getWidth()) / 2;
            int y = (tCont.height - Reservacion.getHeight()) / 2;
            Reservacion.setLocation(x, y);
            panel.revalidate();  // Asegura que el panel se actualice
            panel.repaint();     // Vuelve a dibujar el panel
            Reservacion.setVisible(true);
            lblInicio.setText("Reservas");
        } else if (cboPanel1.getSelectedItem().equals("Solicitudes")) {
            Cerrar();
            Solicitud.setPreferredSize(new Dimension(730, 460));
            panel.add(Solicitud);
            Solicitud.setSize(730, 460);
            Dimension tCont = panel.getSize();
            int x = (tCont.width - Solicitud.getWidth()) / 2;
            int y = (tCont.height - Solicitud.getHeight()) / 2;
            Solicitud.setLocation(x, y);
            panel.revalidate();  // Asegura que el panel se actualice
            panel.repaint();     // Vuelve a dibujar el panel
            Solicitud.setVisible(true);
            lblInicio.setText("Solicitudes");
        } else if (cboPanel1.getSelectedItem().equals("Horarios")) {
            Cerrar();
            Hora.setPreferredSize(new Dimension(730, 460));
            panel.add(Hora);
            Hora.setSize(730, 460);
            Dimension tCont = panel.getSize();
            int x = (tCont.width - Hora.getWidth()) / 2;
            int y = (tCont.height - Hora.getHeight()) / 2;
            Hora.setLocation(x, y);
            panel.revalidate();  // Asegura que el panel se actualice
            panel.repaint();     // Vuelve a dibujar el panel
            Hora.setVisible(true);
            lblInicio.setText("Solicitudes");
        }
    }//GEN-LAST:event_cboPanel1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        obj1.Privilegio = 0;
        obj1.nombre = "";
        obj1.apellido = "";
        obj1.Correo = "";
        Login log = new Login();
        this.hide();
        this.dispose();
        //System.exit(0);
        log.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void cboPanel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPanel2ActionPerformed
        // TODO add your handling code here:
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        if (cboPanel2.getSelectedItem().toString().equals("Reporte de reservas")) {

            Registro.setPreferredSize(new Dimension(730, 460));  // Tamaño preferido
            panel.add(Registro);
            Cerrar();
            // Forzar el tamaño del componente
            Registro.setSize(730, 460); // Establecer el tamaño físico real
            Dimension tCont = panel.getSize();
            // Calcular la posición para centrar el componente
            int x = (tCont.width - Registro.getWidth()) / 2;
            int y = (tCont.height - Registro.getHeight()) / 2;
            // Establecer la ubicación del componente
            Registro.setLocation(x, y);
            // Actualizar la visualización y repintar
            panel.revalidate();  // Asegura que el panel se actualice
            panel.repaint();     // Vuelve a dibujar el panel
            Registro.setVisible(true);
            lblInicio.setText("Historial de reservas");
        }
    }//GEN-LAST:event_cboPanel2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUsuario;
    private javax.swing.JComboBox<String> cboPanel1;
    private javax.swing.JComboBox<String> cboPanel2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblInicios;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
