/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Formularios;

import Clases.WebServiceClient;
import com.mycompany.soapclient.Reserva;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anderson
 */
public class Reservaciones extends javax.swing.JPanel {

    /**
     * Creates new form Encargado_Reservaciones
     */
    public Reservaciones() {
        initComponents();
        mostrarReservasEnTabla();
    }

    WebServiceClient obj1 = new WebServiceClient();

    private void mostrarReservasEnTabla() {
        jTable1.setDefaultEditor(Object.class, null);
        List<Reserva> reservaciones = obj1.obtenerReserva();

        String[] columnNames = {"Correo", "Apellido", "Nombre", "Cancha", "Fecha", "Hora"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);

        for (Reserva reserva : reservaciones) {
            Object[] rowData = {
                reserva.getCorreo() != null && reserva.getCorreo().getValue() != null ? reserva.getCorreo().getValue() : "No disponible",
                reserva.getApellido() != null && reserva.getApellido().getValue() != null ? reserva.getApellido().getValue() : "No disponible",
                reserva.getNombre() != null && reserva.getNombre().getValue() != null ? reserva.getNombre().getValue() : "No disponible",
                reserva.getCancha() != null && reserva.getCancha().getValue() != null ? reserva.getCancha().getValue() : "No disponible",
                reserva.getFechaSolicitada() != null ? reserva.getFechaSolicitada().toString() : "No disponible",
                reserva.getHora() != null ? formatDuration(reserva.getHora().getValue()) : "No disponible"
            };

            model.addRow(rowData);
        }
        jTable1.setModel(model);
    }
    
    private String formatDuration(javax.xml.datatype.Duration duration) {
        long hours = duration.getHours();
        long minutes = duration.getMinutes();
        return String.format("%02d:%02d", hours, minutes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(730, 460));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 690, 400));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setText("Solicitudes aceptadas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton1.setText("Refrescar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        mostrarReservasEnTabla();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
