
package com.mycompany.soapclient;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IService {


    /**
     * 
     * @param value
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetData", action = "http://tempuri.org/IService/GetData")
    @WebResult(name = "GetDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetData", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.GetData")
    @ResponseWrapper(localName = "GetDataResponse", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.GetDataResponse")
    public String getData(
        @WebParam(name = "value", targetNamespace = "http://tempuri.org/")
        Integer value);

    /**
     * 
     * @param composite
     * @return
     *     returns com.mycompany.soapclient.CompositeType
     */
    @WebMethod(operationName = "GetDataUsingDataContract", action = "http://tempuri.org/IService/GetDataUsingDataContract")
    @WebResult(name = "GetDataUsingDataContractResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetDataUsingDataContract", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.GetDataUsingDataContract")
    @ResponseWrapper(localName = "GetDataUsingDataContractResponse", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.GetDataUsingDataContractResponse")
    public CompositeType getDataUsingDataContract(
        @WebParam(name = "composite", targetNamespace = "http://tempuri.org/")
        CompositeType composite);

    /**
     * 
     * @param password
     * @param login
     * @return
     *     returns com.mycompany.soapclient.ArrayOfSesion
     */
    @WebMethod(operationName = "ValidarUsuario", action = "http://tempuri.org/IService/ValidarUsuario")
    @WebResult(name = "ValidarUsuarioResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ValidarUsuario", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.ValidarUsuario")
    @ResponseWrapper(localName = "ValidarUsuarioResponse", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.ValidarUsuarioResponse")
    public ArrayOfSesion validarUsuario(
        @WebParam(name = "login", targetNamespace = "http://tempuri.org/")
        String login,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param password
     * @param estado
     * @param apellido
     * @param login
     * @param telefono
     * @param idPrivilegio
     * @param nombre
     * @param email
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "InsertarUsuario", action = "http://tempuri.org/IService/InsertarUsuario")
    @WebResult(name = "InsertarUsuarioResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "InsertarUsuario", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.InsertarUsuario")
    @ResponseWrapper(localName = "InsertarUsuarioResponse", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.InsertarUsuarioResponse")
    public String insertarUsuario(
        @WebParam(name = "login", targetNamespace = "http://tempuri.org/")
        String login,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "email", targetNamespace = "http://tempuri.org/")
        String email,
        @WebParam(name = "estado", targetNamespace = "http://tempuri.org/")
        Short estado,
        @WebParam(name = "idPrivilegio", targetNamespace = "http://tempuri.org/")
        Integer idPrivilegio,
        @WebParam(name = "nombre", targetNamespace = "http://tempuri.org/")
        String nombre,
        @WebParam(name = "apellido", targetNamespace = "http://tempuri.org/")
        String apellido,
        @WebParam(name = "telefono", targetNamespace = "http://tempuri.org/")
        String telefono);

    /**
     * 
     * @return
     *     returns com.mycompany.soapclient.ArrayOfUsuario
     */
    @WebMethod(operationName = "MostrarDatos", action = "http://tempuri.org/IService/MostrarDatos")
    @WebResult(name = "MostrarDatosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MostrarDatos", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.MostrarDatos")
    @ResponseWrapper(localName = "MostrarDatosResponse", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.MostrarDatosResponse")
    public ArrayOfUsuario mostrarDatos();

    /**
     * 
     * @param idUsuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "EliminarUsuario", action = "http://tempuri.org/IService/EliminarUsuario")
    @WebResult(name = "EliminarUsuarioResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "EliminarUsuario", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.EliminarUsuario")
    @ResponseWrapper(localName = "EliminarUsuarioResponse", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.EliminarUsuarioResponse")
    public String eliminarUsuario(
        @WebParam(name = "idUsuario", targetNamespace = "http://tempuri.org/")
        Integer idUsuario);

    /**
     * 
     * @param estado
     * @param apellido
     * @param login
     * @param telefono
     * @param nombre
     * @param idPrivilegio
     * @param idUsuarios
     * @param email
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ActualizarUsuario", action = "http://tempuri.org/IService/ActualizarUsuario")
    @WebResult(name = "ActualizarUsuarioResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ActualizarUsuario", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.ActualizarUsuario")
    @ResponseWrapper(localName = "ActualizarUsuarioResponse", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.ActualizarUsuarioResponse")
    public String actualizarUsuario(
        @WebParam(name = "IdUsuarios", targetNamespace = "http://tempuri.org/")
        Integer idUsuarios,
        @WebParam(name = "login", targetNamespace = "http://tempuri.org/")
        String login,
        @WebParam(name = "nombre", targetNamespace = "http://tempuri.org/")
        String nombre,
        @WebParam(name = "apellido", targetNamespace = "http://tempuri.org/")
        String apellido,
        @WebParam(name = "email", targetNamespace = "http://tempuri.org/")
        String email,
        @WebParam(name = "telefono", targetNamespace = "http://tempuri.org/")
        String telefono,
        @WebParam(name = "estado", targetNamespace = "http://tempuri.org/")
        Short estado,
        @WebParam(name = "idPrivilegio", targetNamespace = "http://tempuri.org/")
        Integer idPrivilegio);

    /**
     * 
     * @param tipo
     * @param numeroCanchas
     * @param nombre
     * @param estados
     * @return
     *     returns com.mycompany.soapclient.ArrayOfCancha
     */
    @WebMethod(operationName = "MostrarCanchas", action = "http://tempuri.org/IService/MostrarCanchas")
    @WebResult(name = "MostrarCanchasResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MostrarCanchas", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.MostrarCanchas")
    @ResponseWrapper(localName = "MostrarCanchasResponse", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.MostrarCanchasResponse")
    public ArrayOfCancha mostrarCanchas(
        @WebParam(name = "tipo", targetNamespace = "http://tempuri.org/")
        String tipo,
        @WebParam(name = "nombre", targetNamespace = "http://tempuri.org/")
        String nombre,
        @WebParam(name = "numeroCanchas", targetNamespace = "http://tempuri.org/")
        String numeroCanchas,
        @WebParam(name = "estados", targetNamespace = "http://tempuri.org/")
        String estados);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "EliminarCancha", action = "http://tempuri.org/IService/EliminarCancha")
    @WebResult(name = "EliminarCanchaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "EliminarCancha", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.EliminarCancha")
    @ResponseWrapper(localName = "EliminarCanchaResponse", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.EliminarCanchaResponse")
    public String eliminarCancha(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        Integer id);

    /**
     * 
     * @param numeroCancha
     * @param tipo
     * @param ubicacion
     * @param estado
     * @param nombre
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "InsertarCancha", action = "http://tempuri.org/IService/InsertarCancha")
    @WebResult(name = "InsertarCanchaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "InsertarCancha", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.InsertarCancha")
    @ResponseWrapper(localName = "InsertarCanchaResponse", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.InsertarCanchaResponse")
    public String insertarCancha(
        @WebParam(name = "nombre", targetNamespace = "http://tempuri.org/")
        String nombre,
        @WebParam(name = "tipo", targetNamespace = "http://tempuri.org/")
        String tipo,
        @WebParam(name = "ubicacion", targetNamespace = "http://tempuri.org/")
        String ubicacion,
        @WebParam(name = "numeroCancha", targetNamespace = "http://tempuri.org/")
        Integer numeroCancha,
        @WebParam(name = "estado", targetNamespace = "http://tempuri.org/")
        Short estado);

    /**
     * 
     * @param numeroCancha
     * @param tipo
     * @param ubicacion
     * @param estado
     * @param id
     * @param nombre
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ActualizarCancha", action = "http://tempuri.org/IService/ActualizarCancha")
    @WebResult(name = "ActualizarCanchaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ActualizarCancha", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.ActualizarCancha")
    @ResponseWrapper(localName = "ActualizarCanchaResponse", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.ActualizarCanchaResponse")
    public String actualizarCancha(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        Integer id,
        @WebParam(name = "nombre", targetNamespace = "http://tempuri.org/")
        String nombre,
        @WebParam(name = "tipo", targetNamespace = "http://tempuri.org/")
        String tipo,
        @WebParam(name = "ubicacion", targetNamespace = "http://tempuri.org/")
        String ubicacion,
        @WebParam(name = "numeroCancha", targetNamespace = "http://tempuri.org/")
        Integer numeroCancha,
        @WebParam(name = "estado", targetNamespace = "http://tempuri.org/")
        Short estado);

    /**
     * 
     * @param correo
     * @return
     *     returns com.mycompany.soapclient.ArrayOfReservaPendiente
     */
    @WebMethod(operationName = "MostrarSolicitudes", action = "http://tempuri.org/IService/MostrarSolicitudes")
    @WebResult(name = "MostrarSolicitudesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MostrarSolicitudes", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.MostrarSolicitudes")
    @ResponseWrapper(localName = "MostrarSolicitudesResponse", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.MostrarSolicitudesResponse")
    public ArrayOfReservaPendiente mostrarSolicitudes(
        @WebParam(name = "correo", targetNamespace = "http://tempuri.org/")
        String correo);

    /**
     * 
     * @param motivo
     * @param estado
     * @param horaSolicitadaStr
     * @param cancha
     * @param apellido
     * @param correo
     * @param idUsuario
     * @param horaFinalizacionStr
     * @param fechaSolicitadaStr
     * @param nombre
     * @param idCancha
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "InsertarSolicitud", action = "http://tempuri.org/IService/InsertarSolicitud")
    @WebResult(name = "InsertarSolicitudResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "InsertarSolicitud", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.InsertarSolicitud")
    @ResponseWrapper(localName = "InsertarSolicitudResponse", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.InsertarSolicitudResponse")
    public String insertarSolicitud(
        @WebParam(name = "nombre", targetNamespace = "http://tempuri.org/")
        String nombre,
        @WebParam(name = "apellido", targetNamespace = "http://tempuri.org/")
        String apellido,
        @WebParam(name = "correo", targetNamespace = "http://tempuri.org/")
        String correo,
        @WebParam(name = "cancha", targetNamespace = "http://tempuri.org/")
        String cancha,
        @WebParam(name = "fechaSolicitadaStr", targetNamespace = "http://tempuri.org/")
        String fechaSolicitadaStr,
        @WebParam(name = "horaSolicitadaStr", targetNamespace = "http://tempuri.org/")
        String horaSolicitadaStr,
        @WebParam(name = "horaFinalizacionStr", targetNamespace = "http://tempuri.org/")
        String horaFinalizacionStr,
        @WebParam(name = "motivo", targetNamespace = "http://tempuri.org/")
        String motivo,
        @WebParam(name = "estado", targetNamespace = "http://tempuri.org/")
        String estado,
        @WebParam(name = "idUsuario", targetNamespace = "http://tempuri.org/")
        Integer idUsuario,
        @WebParam(name = "idCancha", targetNamespace = "http://tempuri.org/")
        Integer idCancha);

    /**
     * 
     * @param idReservaPendiente
     * @param motivo
     * @param estado
     * @param horaSolicitadaStr
     * @param cancha
     * @param apellido
     * @param correo
     * @param idUsuario
     * @param horaFinalizacionStr
     * @param fechaSolicitadaStr
     * @param nombre
     * @param idCancha
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ActualizarSolicitud", action = "http://tempuri.org/IService/ActualizarSolicitud")
    @WebResult(name = "ActualizarSolicitudResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ActualizarSolicitud", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.ActualizarSolicitud")
    @ResponseWrapper(localName = "ActualizarSolicitudResponse", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.ActualizarSolicitudResponse")
    public String actualizarSolicitud(
        @WebParam(name = "idReservaPendiente", targetNamespace = "http://tempuri.org/")
        Integer idReservaPendiente,
        @WebParam(name = "nombre", targetNamespace = "http://tempuri.org/")
        String nombre,
        @WebParam(name = "apellido", targetNamespace = "http://tempuri.org/")
        String apellido,
        @WebParam(name = "correo", targetNamespace = "http://tempuri.org/")
        String correo,
        @WebParam(name = "cancha", targetNamespace = "http://tempuri.org/")
        String cancha,
        @WebParam(name = "fechaSolicitadaStr", targetNamespace = "http://tempuri.org/")
        String fechaSolicitadaStr,
        @WebParam(name = "horaSolicitadaStr", targetNamespace = "http://tempuri.org/")
        String horaSolicitadaStr,
        @WebParam(name = "horaFinalizacionStr", targetNamespace = "http://tempuri.org/")
        String horaFinalizacionStr,
        @WebParam(name = "motivo", targetNamespace = "http://tempuri.org/")
        String motivo,
        @WebParam(name = "estado", targetNamespace = "http://tempuri.org/")
        String estado,
        @WebParam(name = "idUsuario", targetNamespace = "http://tempuri.org/")
        Integer idUsuario,
        @WebParam(name = "idCancha", targetNamespace = "http://tempuri.org/")
        Integer idCancha);

    /**
     * 
     * @param idReservaPendiente
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "EliminarSolicitud", action = "http://tempuri.org/IService/EliminarSolicitud")
    @WebResult(name = "EliminarSolicitudResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "EliminarSolicitud", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.EliminarSolicitud")
    @ResponseWrapper(localName = "EliminarSolicitudResponse", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.EliminarSolicitudResponse")
    public String eliminarSolicitud(
        @WebParam(name = "idReservaPendiente", targetNamespace = "http://tempuri.org/")
        Integer idReservaPendiente);

    /**
     * 
     * @param horaInicialStr
     * @param cancha
     * @param fechaStr
     * @param horaFinalStr
     * @param idCancha
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "InsertarHorario", action = "http://tempuri.org/IService/InsertarHorario")
    @WebResult(name = "InsertarHorarioResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "InsertarHorario", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.InsertarHorario")
    @ResponseWrapper(localName = "InsertarHorarioResponse", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.InsertarHorarioResponse")
    public String insertarHorario(
        @WebParam(name = "idCancha", targetNamespace = "http://tempuri.org/")
        Integer idCancha,
        @WebParam(name = "cancha", targetNamespace = "http://tempuri.org/")
        String cancha,
        @WebParam(name = "fechaStr", targetNamespace = "http://tempuri.org/")
        String fechaStr,
        @WebParam(name = "horaInicialStr", targetNamespace = "http://tempuri.org/")
        String horaInicialStr,
        @WebParam(name = "horaFinalStr", targetNamespace = "http://tempuri.org/")
        String horaFinalStr);

    /**
     * 
     * @param horaInicial
     * @param cancha
     * @param horaFinal
     * @param dia
     * @return
     *     returns com.mycompany.soapclient.ArrayOfHorario
     */
    @WebMethod(operationName = "MostrarHorarios", action = "http://tempuri.org/IService/MostrarHorarios")
    @WebResult(name = "MostrarHorariosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MostrarHorarios", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.MostrarHorarios")
    @ResponseWrapper(localName = "MostrarHorariosResponse", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.MostrarHorariosResponse")
    public ArrayOfHorario mostrarHorarios(
        @WebParam(name = "dia", targetNamespace = "http://tempuri.org/")
        String dia,
        @WebParam(name = "cancha", targetNamespace = "http://tempuri.org/")
        String cancha,
        @WebParam(name = "horaInicial", targetNamespace = "http://tempuri.org/")
        String horaInicial,
        @WebParam(name = "horaFinal", targetNamespace = "http://tempuri.org/")
        String horaFinal);

    /**
     * 
     * @param idHorario
     * @param horaInicialStr
     * @param cancha
     * @param horaFinalStr
     * @param diaStr
     * @param idCancha
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ActualizarHorario", action = "http://tempuri.org/IService/ActualizarHorario")
    @WebResult(name = "ActualizarHorarioResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ActualizarHorario", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.ActualizarHorario")
    @ResponseWrapper(localName = "ActualizarHorarioResponse", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.ActualizarHorarioResponse")
    public String actualizarHorario(
        @WebParam(name = "idHorario", targetNamespace = "http://tempuri.org/")
        Integer idHorario,
        @WebParam(name = "idCancha", targetNamespace = "http://tempuri.org/")
        Integer idCancha,
        @WebParam(name = "cancha", targetNamespace = "http://tempuri.org/")
        String cancha,
        @WebParam(name = "diaStr", targetNamespace = "http://tempuri.org/")
        String diaStr,
        @WebParam(name = "horaInicialStr", targetNamespace = "http://tempuri.org/")
        String horaInicialStr,
        @WebParam(name = "horaFinalStr", targetNamespace = "http://tempuri.org/")
        String horaFinalStr);

    /**
     * 
     * @param idHorario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "EliminarHorario", action = "http://tempuri.org/IService/EliminarHorario")
    @WebResult(name = "EliminarHorarioResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "EliminarHorario", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.EliminarHorario")
    @ResponseWrapper(localName = "EliminarHorarioResponse", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.EliminarHorarioResponse")
    public String eliminarHorario(
        @WebParam(name = "IdHorario", targetNamespace = "http://tempuri.org/")
        Integer idHorario);

    /**
     * 
     * @param estadoReserva
     * @return
     *     returns com.mycompany.soapclient.ArrayOfHistorialReserva
     */
    @WebMethod(operationName = "MostrarHistorialReservas", action = "http://tempuri.org/IService/MostrarHistorialReservas")
    @WebResult(name = "MostrarHistorialReservasResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MostrarHistorialReservas", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.MostrarHistorialReservas")
    @ResponseWrapper(localName = "MostrarHistorialReservasResponse", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.MostrarHistorialReservasResponse")
    public ArrayOfHistorialReserva mostrarHistorialReservas(
        @WebParam(name = "estadoReserva", targetNamespace = "http://tempuri.org/")
        String estadoReserva);

    /**
     * 
     * @return
     *     returns com.mycompany.soapclient.ArrayOfReserva
     */
    @WebMethod(operationName = "MostrarReservas", action = "http://tempuri.org/IService/MostrarReservas")
    @WebResult(name = "MostrarReservasResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MostrarReservas", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.MostrarReservas")
    @ResponseWrapper(localName = "MostrarReservasResponse", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.MostrarReservasResponse")
    public ArrayOfReserva mostrarReservas();

    /**
     * 
     * @param nombre
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "InsertarTipo", action = "http://tempuri.org/IService/InsertarTipo")
    @WebResult(name = "InsertarTipoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "InsertarTipo", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.InsertarTipo")
    @ResponseWrapper(localName = "InsertarTipoResponse", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.InsertarTipoResponse")
    public String insertarTipo(
        @WebParam(name = "nombre", targetNamespace = "http://tempuri.org/")
        String nombre);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "EliminarTipo", action = "http://tempuri.org/IService/EliminarTipo")
    @WebResult(name = "EliminarTipoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "EliminarTipo", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.EliminarTipo")
    @ResponseWrapper(localName = "EliminarTipoResponse", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.EliminarTipoResponse")
    public String eliminarTipo(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        Integer id);

    /**
     * 
     * @param id
     * @param nombre
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ActualizarTipo", action = "http://tempuri.org/IService/ActualizarTipo")
    @WebResult(name = "ActualizarTipoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ActualizarTipo", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.ActualizarTipo")
    @ResponseWrapper(localName = "ActualizarTipoResponse", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.ActualizarTipoResponse")
    public String actualizarTipo(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        Integer id,
        @WebParam(name = "nombre", targetNamespace = "http://tempuri.org/")
        String nombre);

    /**
     * 
     * @return
     *     returns com.mycompany.soapclient.ArrayOfTipo
     */
    @WebMethod(operationName = "MostrarTipos", action = "http://tempuri.org/IService/MostrarTipos")
    @WebResult(name = "MostrarTiposResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MostrarTipos", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.MostrarTipos")
    @ResponseWrapper(localName = "MostrarTiposResponse", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.MostrarTiposResponse")
    public ArrayOfTipo mostrarTipos();

    /**
     * 
     * @param newPassword
     * @param login
     * @param email
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ActualizarContrasena", action = "http://tempuri.org/IService/ActualizarContrasena")
    @WebResult(name = "ActualizarContrasenaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ActualizarContrasena", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.ActualizarContrasena")
    @ResponseWrapper(localName = "ActualizarContrasenaResponse", targetNamespace = "http://tempuri.org/", className = "com.mycompany.soapclient.ActualizarContrasenaResponse")
    public String actualizarContrasena(
        @WebParam(name = "login", targetNamespace = "http://tempuri.org/")
        String login,
        @WebParam(name = "email", targetNamespace = "http://tempuri.org/")
        String email,
        @WebParam(name = "newPassword", targetNamespace = "http://tempuri.org/")
        String newPassword);

}
